# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd9483811717c78b18408bc933e01fe2283fc1311c350a095d877498cb3d26266ca784fcf9804440536ad1cadbd098933d9ffd51b4e4756f02d0b984128902c

test:
  secret_key_base: 16d6c4fc83b98508e5cf9fc46fab272ddda2a2a6409b3646b92c1849a687609bdc3a6cf83b4ae2f559e42a095dfc08856acc1811a94c1bc933e70129f56e451a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
